import json, re, os
SP = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(SP, "..", "src", "04g-catalog-data.js")

# ---------------------------------------------------------------- icon grouping
GROUPS = [
    ("Water & hydrology", r"water|waterfall|wetland|swamp|dam|fountain|spring|harbor|harbour|slipway|ferry|boat|canoe|kayak|rafting|sail|pier|quay|buoy|anchor|fish|coral|lighthouse|geyser|islet|beach|surf|diving|scuba|jet_ski|watermill|drinking|shower|fish_ladder"),
    ("Terrain & nature", r"mountain|volcano|cliff|valley|cape|natural|cave|boulder|cairn|rock|landform|arch|snow|glacier|globe|island"),
    ("Vegetation & forest", r"tree|shrub|grass|lawn|garden|park|wood|forest|plant|hedge|logging|cactus|palm|leaf|needle|farm|grapes"),
    ("Transport", r"airport|airfield|heliport|aerial|rail|train|tram|subway|metro|bus|taxi|car|parking|fuel|charging|bicycle|scooter|motorcycle|truck|road|highway|toll|tunnel|bridge|terminal|transit|gate|lift_gate|barrier|crossing|kerb|traffic|speed|junction|stop|gondola|chairlift|cable_car|monorail|trolley|plane|jet|freight|buffer|elevator|entrance|wheelchair|pedestrian|cyclist|rocket|roadblock|turnstile|bollard|chicane"),
    ("Government & public", r"town|city|village|capitol|courthouse|embassy|police|prison|post|letter|military|army|fire|rescue|ranger|town-hall|town_hall|checkpoint|passport|border|flag|shield|bunker|military_checkpoint|telephone|emergency|defibrillator"),
    ("Health", r"hospital|doctor|pharmacy|dentist|clinic|blood|veterinary|optician|hearing|physio|heart|medical|ambulance"),
    ("Education & culture", r"school|college|library|museum|book|theatre|cinema|art|gallery|music|monument|historic|castle|ruins|statue|sculpture|obelisk|memorial|plaque|landmark|marae|paifang"),
    ("Religion", r"religious|worship|church|mosque|temple|shinto|hinduism|sikhism|taoism|quaker|cemetery|grave"),
    ("Tourism & recreation", r"attraction|viewpoint|observation|picnic|campsite|camp|tent|lodging|hotel|hut|cabin|shelter|information|info_board|zoo|aquarium|amusement|playground|play|swing|slide|sandbox|maze|roller|binocular|telescope|spotting|casino|karaoke|nightclub|bbq|campfire|hot-spring|spa"),
    ("Sports", r"soccer|football|baseball|basketball|tennis|golf|swimming|stadium|pitch|skiing|ski|skate|horse|racetrack|speedway|bowling|cricket|volleyball|archery|climbing|fitness|gym|sport|table-tennis|pickleball|disc_golf|field_hockey|hang_gliding|abseiling|snowboard|sledding|ice|balance_beam|horizontal_bar|trampoline|shuffleboard|abseil"),
    ("Food & shops", r"restaurant|cafe|coffee|bar|beer|alcohol|bakery|bread|fast-food|food|ice-cream|teahouse|confectionery|chocolate|donut|grocery|shop|store|mall|convenience|clothing|shoe|jewelry|florist|gift|furniture|hardware|optician|hairdresser|beauty|laundry|bank|atm|money|vending|market|meat|milk|catering|bubble|hotpot|sandwich|spice"),
    ("Utilities & industry", r"industry|warehouse|power|electric|cable|gas|pipe|oil|mast|antenna|tower|communication|radio|silo|storage|tank|cooling|radiation|construction|crane|bulldozer|scaffold|mine|adit|quarry|manhole|meter|utility|recycling|waste|windmill|slaughterhouse|commercial|residential|building|home|row_houses|manufactured|barn|chimney|street_lamp|lamp|bulb|trench"),
    ("Hazards & warnings", r"danger|caution|accident|hazard|warning|cliff_falling|fire_hydrant|security|radiation|road-accident"),
    ("Basic symbols", r"^(circle|circle-stroked|square|square-stroked|triangle|triangle-stroked|star|star-stroked|marker|marker-stroked|diamond|cross|arrow|heart|pin|asterisk|temaki|compass)$"),
]
def group_of(name):
    n = name.lower()
    for g, rx in GROUPS[::-1] if False else GROUPS:
        if g == "Basic symbols":
            continue
    # basic symbols first (exact)
    if re.match(GROUPS[-1][1], n):
        return "Basic symbols"
    for g, rx in GROUPS[:-1]:
        if re.search(rx, n):
            return g
    return "Other"

icon_sets = {}
for key, fname, label, ver, pkg in [
    ("maki", "maki_names.json", "Maki", "8.2.0", "@mapbox/maki"),
    ("temaki", "temaki_names.json", "Temaki", "5.13.0", "@rapideditor/temaki"),
]:
    names = json.load(open(os.path.join(SP, fname)))
    groups = {}
    for n in names:
        groups.setdefault(group_of(n), []).append(n)
    icon_sets[key] = {"label": label, "license": "CC0-1.0", "url": f"https://cdn.jsdelivr.net/npm/{pkg}@{ver}/icons/{{name}}.svg", "groups": groups}

data = {"iconSets": icon_sets}
js = "// ---------------------------------------------------------------- icon catalog data (generated by tools/build_catalog.py)\n"
js += "const CATALOG = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n"
open(OUT, "w", encoding="utf8").write(js)
print("bytes", len(js))
